In [1]:
import math
math.exp(math.log(10))

10.000000000000002

In [3]:
True and True is False

False

In [3]:
import math
(math.exp(1)**math.factorial(5))/(13**2 + math.sin(2.2*math.pi))

7.690299607683533e+49

In [9]:
a_string = "The owls are not what they seem."
a_string[9:4:-2]

'asw'

In [1]:
import numpy as np
an_array = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ]
)
sub_array = an_array[0::2, 1::2]
sub_array[1, 0]

np.int64(10)

In [2]:
sub_array


array([[ 2,  4],
       [10, 12]])

In [5]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
y = x.reshape((2, 6))
row_size, col_size = y.shape  # row_size = 2, col_size = 6
z = y[::row_size-1, ::col_size-1]
z


array([[ 1,  6],
       [ 7, 12]])

In [6]:
import numpy as np
arr = np.zeros((5, 6))
arr[[0,0,-1,-1],[0,-1,0,-1]] = 1
arr


array([[1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1.]])

In [7]:
# Block 2
import numpy as np
arr = np.zeros((5, 6))
x = arr[[0,0,-1,-1],[0,-1,0,-1]]
x[:] = 1
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:

# Block 3
import numpy as np
arr = np.zeros((5, 6))
x_len, y_len = arr.shape
x = arr[::x_len-1,::y_len-1]
x[:] = 1
x

array([[1., 1.],
       [1., 1.]])